name: Test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip]') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build
      run: ./gradlew build